/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ilerna_academy;

import static com.sun.java.accessibility.util.AWTEventMonitor.addKeyListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
/**
 *
 * @author alumno
 */
public class tema1 extends javax.swing.JFrame {

    /**
     * Creates new form tema1
     */
    int x=0;
    int x2=0;
    public tema1() {
        initComponents();
        avanzar.setVisible(false);
        x2=Segundanube.getX();
        addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
              
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
                   System.out.println(x);
                   System.out.println(x2 + " SEGUNDA");
                   
                  if(x <= -650) {
                      avanzar.setVisible(true);
                  }else{
                    x-=10;
                    x2-=10;
                     pancarta.setLocation(pancarta.getX() -10, pancarta.getY());
                    pancarta1.setLocation(pancarta1.getX() -10, pancarta1.getY());
                    Helicoptero.setLocation(Helicoptero.getX() -10, Helicoptero.getY());
                   Primeranube.setLocation(x ,0);
                   Segundanube.setLocation(x2, 0);
                   
                  }
                }
                
                if (e.getKeyCode() == KeyEvent.VK_LEFT) {  
                    
                    if (x >= 0) {
                        x= 0;
                        Primeranube.setLocation(x, 0);
                        Segundanube.setLocation(x2, 0);

                        System.out.println(x);
                    }else{
                        x += 10;
                        x2 += 10;
                    pancarta.setLocation(pancarta.getX() +10, pancarta.getY());
                    pancarta1.setLocation(pancarta1.getX() +10, pancarta1.getY());
                    Helicoptero.setLocation(Helicoptero.getX() +10, Helicoptero.getY());
                        Primeranube.setLocation(x, 0);
                        Segundanube.setLocation(x2, 0);
                    }
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pancarta = new javax.swing.JTextField();
        pancarta1 = new javax.swing.JTextField();
        Helicoptero = new javax.swing.JLabel();
        avanzar = new javax.swing.JButton();
        Segundanube = new javax.swing.JLabel();
        Primeranube = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pancarta.setBackground(new java.awt.Color(255, 255, 153));
        pancarta.setForeground(new java.awt.Color(0, 0, 0));
        pancarta.setText("Es decir, si vamos a usar la variable para almacenar un apellido, lo mejor es llamarlo así. Ej: String apellido; int n_jugadores; Podemos simplemente dejar el contenedor “vacío” para llenarlo más adelante. int: números enteros boolean: puede tomar dos valores (true o false) char: un caracter String: cadena de caracteres ");
        pancarta.setFocusable(false);
        pancarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pancartaActionPerformed(evt);
            }
        });
        getContentPane().add(pancarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 1690, 70));

        pancarta1.setBackground(new java.awt.Color(255, 255, 153));
        pancarta1.setForeground(new java.awt.Color(0, 0, 0));
        pancarta1.setText("Para declarar una variable indicaremos primero el tipo y después un nombre, el que queramos. Las dos únicas normas para definirlo es que no empiece por un número, ni contenga espacios, aunque también se recomienda que sea aclarativo.");
        pancarta1.setFocusable(false);
        pancarta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pancarta1ActionPerformed(evt);
            }
        });
        getContentPane().add(pancarta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 1690, 70));

        Helicoptero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Helicoptero_ilerna (1).png"))); // NOI18N
        getContentPane().add(Helicoptero, new org.netbeans.lib.awtextra.AbsoluteConstraints(2130, 40, 320, 260));

        avanzar.setBackground(new java.awt.Color(255, 255, 255));
        avanzar.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        avanzar.setText("Siguiente");
        avanzar.setToolTipText("");
        avanzar.setFocusable(false);
        avanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzarActionPerformed(evt);
            }
        });
        getContentPane().add(avanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 680, -1, -1));

        Segundanube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nubes4 (1).png"))); // NOI18N
        getContentPane().add(Segundanube, new org.netbeans.lib.awtextra.AbsoluteConstraints(1279, 0, 1280, 720));

        Primeranube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nubes1 (1).png"))); // NOI18N
        Primeranube.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrimeranubeKeyPressed(evt);
            }
        });
        getContentPane().add(Primeranube, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void PrimeranubeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrimeranubeKeyPressed
      
    }//GEN-LAST:event_PrimeranubeKeyPressed

    private void avanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzarActionPerformed
       Test test =  new Test();
               test.setVisible(true);
               this.dispose();
    }//GEN-LAST:event_avanzarActionPerformed

    private void pancartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pancartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pancartaActionPerformed

    private void pancarta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pancarta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pancarta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new tema1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Helicoptero;
    private javax.swing.JLabel Primeranube;
    private javax.swing.JLabel Segundanube;
    private javax.swing.JButton avanzar;
    private javax.swing.JTextField pancarta;
    private javax.swing.JTextField pancarta1;
    // End of variables declaration//GEN-END:variables
}
