/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ilerna_academy;
import java.sql.Statement;

/**
 *
 * @author alumno
 */
public class usuario extends javax.swing.JFrame {
    
    static Conexion con = new Conexion();

    /**
     * Creates new form usuario
     */
    public usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        ingresar = new javax.swing.JButton();
        ilerna1 = new javax.swing.JButton();
        Introducir_nombre = new javax.swing.JLabel();
        niña2 = new javax.swing.JLabel();
        niña = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 400, -1));

        ingresar.setBackground(new java.awt.Color(255, 255, 255));
        ingresar.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 150, 50));

        ilerna1.setBackground(new java.awt.Color(255, 255, 255));
        ilerna1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ilernasevilla (1).png"))); // NOI18N
        ilerna1.setBorder(null);
        getContentPane().add(ilerna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 160, 90));

        Introducir_nombre.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Introducir_nombre.setText("Introduzca su nombre para empezar a jugar");
        getContentPane().add(Introducir_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        niña2.setIcon(new javax.swing.ImageIcon("C:\\Users\\alumno\\Downloads\\niña2 (1).png")); // NOI18N
        getContentPane().add(niña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 150, 120));

        niña.setIcon(new javax.swing.ImageIcon("C:\\Users\\alumno\\Downloads\\niña (1).png")); // NOI18N
        getContentPane().add(niña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 150, 120));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\alumno\\Downloads\\logo_ilerna (1).png")); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 200, 170));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blanco.PNG"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
                
                
                
        
    }//GEN-LAST:event_nombreActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        cuenta.nombreUsuario = nombre.getText();
                System.out.println(nombre.getText());
                
                con.IniciarSesion(cuenta.nombreUsuario);    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
                
                this.dispose();
    }//GEN-LAST:event_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }        
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);           
        
   

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Introducir_nombre;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ilerna1;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel niña;
    private javax.swing.JLabel niña2;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
